// Mocks generated by Mockito 5.4.6 from annotations
// in tsmusic/test/web_music_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:collection' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoSearchList_4 extends _i1.SmartFake
    implements _i6.VideoSearchList {
  _FakeVideoSearchList_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchList_5 extends _i1.SmartFake implements _i6.SearchList {
  _FakeSearchList_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchQuery_6 extends _i1.SmartFake implements _i6.SearchQuery {
  _FakeSearchQuery_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamClient_7 extends _i1.SmartFake implements _i6.StreamClient {
  _FakeStreamClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClosedCaptionClient_8 extends _i1.SmartFake
    implements _i6.ClosedCaptionClient {
  _FakeClosedCaptionClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsClient_9 extends _i1.SmartFake
    implements _i6.CommentsClient {
  _FakeCommentsClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideo_10 extends _i1.SmartFake implements _i6.Video {
  _FakeVideo_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManifest_11 extends _i1.SmartFake
    implements _i6.StreamManifest {
  _FakeStreamManifest_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoId_12 extends _i1.SmartFake implements _i6.VideoId {
  _FakeVideoId_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelId_13 extends _i1.SmartFake implements _i4.ChannelId {
  _FakeChannelId_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThumbnailSet_14 extends _i1.SmartFake implements _i6.ThumbnailSet {
  _FakeThumbnailSet_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_15<E> extends _i1.SmartFake
    implements _i7.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEngagement_16 extends _i1.SmartFake implements _i6.Engagement {
  _FakeEngagement_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$VideoCopyWith_17<$Res> extends _i1.SmartFake
    implements _i6.$VideoCopyWith<$Res> {
  _Fake$VideoCopyWith_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i6.YoutubeExplode {
  MockYoutubeExplode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VideoClient get videos => (super.noSuchMethod(
        Invocation.getter(#videos),
        returnValue: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
      ) as _i2.VideoClient);

  @override
  _i3.PlaylistClient get playlists => (super.noSuchMethod(
        Invocation.getter(#playlists),
        returnValue: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
      ) as _i3.PlaylistClient);

  @override
  _i4.ChannelClient get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i4.ChannelClient);

  @override
  _i5.SearchClient get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
      ) as _i5.SearchClient);

  @override
  set videos(_i2.VideoClient? value) => super.noSuchMethod(
        Invocation.setter(
          #videos,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set playlists(_i3.PlaylistClient? value) => super.noSuchMethod(
        Invocation.setter(
          #playlists,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set channels(_i4.ChannelClient? value) => super.noSuchMethod(
        Invocation.setter(
          #channels,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set search(_i5.SearchClient? value) => super.noSuchMethod(
        Invocation.setter(
          #search,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SearchClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchClient extends _i1.Mock implements _i5.SearchClient {
  MockSearchClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.VideoSearchList> search(
    String? searchQuery, {
    _i6.SearchFilter? filter = _i6.TypeFilters.video,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue:
            _i8.Future<_i6.VideoSearchList>.value(_FakeVideoSearchList_4(
          this,
          Invocation.method(
            #search,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.VideoSearchList>);

  @override
  _i8.Future<_i6.VideoSearchList> getVideos(
    String? searchQuery, {
    _i6.SearchFilter? filter = _i6.TypeFilters.video,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue:
            _i8.Future<_i6.VideoSearchList>.value(_FakeVideoSearchList_4(
          this,
          Invocation.method(
            #getVideos,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.VideoSearchList>);

  @override
  _i8.Future<_i6.SearchList> searchContent(
    String? searchQuery, {
    _i6.SearchFilter? filter = const _i6.SearchFilter(''),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchContent,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue: _i8.Future<_i6.SearchList>.value(_FakeSearchList_5(
          this,
          Invocation.method(
            #searchContent,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.SearchList>);

  @override
  _i8.Future<_i6.VideoSearchList> call(
    String? searchQuery, {
    _i6.SearchFilter? filter = const _i6.SearchFilter(''),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue:
            _i8.Future<_i6.VideoSearchList>.value(_FakeVideoSearchList_4(
          this,
          Invocation.method(
            #call,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.VideoSearchList>);

  @override
  _i8.Future<List<String>> getQuerySuggestions(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuerySuggestions,
          [query],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i6.SearchQuery> searchRaw(
    String? searchQuery, {
    _i6.SearchFilter? filter = const _i6.SearchFilter(''),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaw,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue: _i8.Future<_i6.SearchQuery>.value(_FakeSearchQuery_6(
          this,
          Invocation.method(
            #searchRaw,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.SearchQuery>);

  @override
  _i8.Future<_i6.SearchQuery> queryFromPage(
    String? searchQuery, {
    _i6.SearchFilter? filter = const _i6.SearchFilter(''),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryFromPage,
          [searchQuery],
          {#filter: filter},
        ),
        returnValue: _i8.Future<_i6.SearchQuery>.value(_FakeSearchQuery_6(
          this,
          Invocation.method(
            #queryFromPage,
            [searchQuery],
            {#filter: filter},
          ),
        )),
      ) as _i8.Future<_i6.SearchQuery>);
}

/// A class which mocks [VideoClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoClient extends _i1.Mock implements _i2.VideoClient {
  MockVideoClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.StreamClient get streamsClient => (super.noSuchMethod(
        Invocation.getter(#streamsClient),
        returnValue: _FakeStreamClient_7(
          this,
          Invocation.getter(#streamsClient),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.StreamClient get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakeStreamClient_7(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.ClosedCaptionClient get closedCaptions => (super.noSuchMethod(
        Invocation.getter(#closedCaptions),
        returnValue: _FakeClosedCaptionClient_8(
          this,
          Invocation.getter(#closedCaptions),
        ),
      ) as _i6.ClosedCaptionClient);

  @override
  _i6.CommentsClient get commentsClient => (super.noSuchMethod(
        Invocation.getter(#commentsClient),
        returnValue: _FakeCommentsClient_9(
          this,
          Invocation.getter(#commentsClient),
        ),
      ) as _i6.CommentsClient);

  @override
  _i6.CommentsClient get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsClient_9(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i6.CommentsClient);

  @override
  _i8.Future<_i6.Video> get(dynamic videoId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [videoId],
        ),
        returnValue: _i8.Future<_i6.Video>.value(_FakeVideo_10(
          this,
          Invocation.method(
            #get,
            [videoId],
          ),
        )),
      ) as _i8.Future<_i6.Video>);

  @override
  _i8.Future<_i6.RelatedVideosList?> getRelatedVideos(_i6.Video? video) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedVideos,
          [video],
        ),
        returnValue: _i8.Future<_i6.RelatedVideosList?>.value(),
      ) as _i8.Future<_i6.RelatedVideosList?>);
}

/// A class which mocks [StreamClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamClient extends _i1.Mock implements _i6.StreamClient {
  MockStreamClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.StreamManifest> getManifest(
    dynamic videoId, {
    bool? fullManifest = false,
    List<_i6.YoutubeApiClient>? ytClients,
    bool? requireWatchPage = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManifest,
          [videoId],
          {
            #fullManifest: fullManifest,
            #ytClients: ytClients,
            #requireWatchPage: requireWatchPage,
          },
        ),
        returnValue:
            _i8.Future<_i6.StreamManifest>.value(_FakeStreamManifest_11(
          this,
          Invocation.method(
            #getManifest,
            [videoId],
            {
              #fullManifest: fullManifest,
              #ytClients: ytClients,
              #requireWatchPage: requireWatchPage,
            },
          ),
        )),
      ) as _i8.Future<_i6.StreamManifest>);

  @override
  _i8.Future<String> getHttpLiveStreamUrl(_i6.VideoId? videoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHttpLiveStreamUrl,
          [videoId],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getHttpLiveStreamUrl,
            [videoId],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Stream<List<int>> get(_i6.StreamInfo? streamInfo) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [streamInfo],
        ),
        returnValue: _i8.Stream<List<int>>.empty(),
      ) as _i8.Stream<List<int>>);
}

/// A class which mocks [Video].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideo extends _i1.Mock implements _i6.Video {
  MockVideo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  bool get hasWatchPage => (super.noSuchMethod(
        Invocation.getter(#hasWatchPage),
        returnValue: false,
      ) as bool);

  @override
  _i6.VideoId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeVideoId_12(
          this,
          Invocation.getter(#id),
        ),
      ) as _i6.VideoId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get author => (super.noSuchMethod(
        Invocation.getter(#author),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
      ) as String);

  @override
  _i4.ChannelId get channelId => (super.noSuchMethod(
        Invocation.getter(#channelId),
        returnValue: _FakeChannelId_13(
          this,
          Invocation.getter(#channelId),
        ),
      ) as _i4.ChannelId);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  _i6.ThumbnailSet get thumbnails => (super.noSuchMethod(
        Invocation.getter(#thumbnails),
        returnValue: _FakeThumbnailSet_14(
          this,
          Invocation.getter(#thumbnails),
        ),
      ) as _i6.ThumbnailSet);

  @override
  _i7.UnmodifiableListView<String> get keywords => (super.noSuchMethod(
        Invocation.getter(#keywords),
        returnValue: _FakeUnmodifiableListView_15<String>(
          this,
          Invocation.getter(#keywords),
        ),
      ) as _i7.UnmodifiableListView<String>);

  @override
  _i6.Engagement get engagement => (super.noSuchMethod(
        Invocation.getter(#engagement),
        returnValue: _FakeEngagement_16(
          this,
          Invocation.getter(#engagement),
        ),
      ) as _i6.Engagement);

  @override
  bool get isLive => (super.noSuchMethod(
        Invocation.getter(#isLive),
        returnValue: false,
      ) as bool);

  @override
  List<({String? album, String? artist, Uri? image, String? song})>
      get musicData => (super.noSuchMethod(
            Invocation.getter(#musicData),
            returnValue: <({
              String? album,
              String? artist,
              Uri? image,
              String? song
            })>[],
          ) as List<
              ({String? album, String? artist, Uri? image, String? song})>);

  @override
  _i6.$VideoCopyWith<_i6.Video> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$VideoCopyWith_17<_i6.Video>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i6.$VideoCopyWith<_i6.Video>);
}
