# Flutter/Dart Analysis Options
# See: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/generated_*'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    # Enable stricter analysis in lib/
    # invalid_assignment: error
    # invalid_override: error
    # invalid_return_type_for_catch_error: error
    # missing_return: error
    # throw_in_finally: error

linter:
  rules:
    # Style
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_relative_lib_imports: true
    avoid_web_libraries_in_flutter: true
    avoid_empty_else: true
    avoid_print: true
    avoid_returning_null_for_void: true
    avoid_unused_imports: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    no_leading_underscores_for_local_identifiers: true
    no_logic_in_create_state: true
    prefer_adjacent_string_concatenation: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_foreach: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sort_child_properties_last: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true
