name: tsmusic
description: "A Flutter app for playing and downloading music."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.11

  # Audio
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  just_audio_background: ^0.0.1-beta.14
  audio_service: ^0.18.17

  # File Access
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  path: ^1.9.0
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  cached_network_image: ^3.4.1
  vector_math: ^2.1.4

  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.0
  sqflite: ^2.3.0

  # Theming
  flex_color_scheme: ^8.2.0
  rxdart: ^0.28.0
  
  # YouTube
  youtube_explode_dart: ^2.1.1
  http: ^1.1.0
  
  # Desktop
  window_manager: ^0.3.9
  
  # UI components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
