name: Release Build

on:
  push:
    tags:
      - 'v*' # Sadece v1.0.1 gibi etiketlerde çalışır
  workflow_dispatch: # Manuel çalıştırmak istersen

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Prepare Versioning
        id: versioning
        run: |
          # Etiket 'v1.2.3' ise '1.2.3' yapar
          VERSION_NAME=${GITHUB_REF#refs/tags/v}
          
          # Eğer manuel tetiklendiyse ve tag yoksa pubspec'ten çek
          if [[ "$VERSION_NAME" == "$GITHUB_REF" ]]; then
            VERSION_NAME=$(grep "^version:" pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
          fi
          
          # Build numarasını GitHub'ın koşu numarasından al (+6 ofsetini ekledim)
          BUILD_NUMBER=$(( ${{ github.run_number }} + 6 ))
          
          echo "v_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "v_num=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Build APK
        run: |
          flutter build apk --release \
            --build-name=${{ steps.versioning.outputs.v_name }} \
            --build-number=${{ steps.versioning.outputs.v_num }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: "Sürüm ${{ steps.versioning.outputs.v_name }}"
          body: "Otomatik Build - No: ${{ steps.versioning.outputs.v_num }}"
          draft: false
          prerelease: false

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsmusic-release-${{ steps.versioning.outputs.v_name }}
          path: build/app/outputs/flutter-apk/app-release.apk